
export interface Country {
  value: string;
  label: string;
  flag: string;
}

export const defaultCountries: Country[] = [
  { value: "ae", label: "United Arab Emirates", flag: "🇦🇪" },
  { value: "ar", label: "Argentina", flag: "🇦🇷" },
  { value: "au", label: "Australia", flag: "🇦🇺" },
  { value: "at", label: "Austria", flag: "🇦🇹" },
  { value: "be", label: "Belgium", flag: "🇧🇪" },
  { value: "br", label: "Brazil", flag: "🇧🇷" },
  { value: "ca", label: "Canada", flag: "🇨🇦" },
  { value: "cl", label: "Chile", flag: "🇨🇱" },
  { value: "cn", label: "China", flag: "🇨🇳" },
  { value: "co", label: "Colombia", flag: "🇨🇴" },
  { value: "hr", label: "Croatia", flag: "🇭🇷" },
  { value: "cz", label: "Czech Republic", flag: "🇨🇿" },
  { value: "dk", label: "Denmark", flag: "🇩🇰" },
  { value: "eg", label: "Egypt", flag: "🇪🇬" },
  { value: "fr", label: "France", flag: "🇫🇷" },
  { value: "de", label: "Germany", flag: "🇩🇪" },
  { value: "gr", label: "Greece", flag: "🇬🇷" },
  { value: "hu", label: "Hungary", flag: "🇭🇺" },
  { value: "in", label: "India", flag: "🇮🇳" },
  { value: "id", label: "Indonesia", flag: "🇮🇩" },
  { value: "ie", label: "Ireland", flag: "🇮🇪" },
  { value: "it", label: "Italy", flag: "🇮🇹" },
  { value: "jp", label: "Japan", flag: "🇯🇵" },
  { value: "ke", label: "Kenya", flag: "🇰🇪" },
  { value: "kw", label: "Kuwait", flag: "🇰🇼" },
  { value: "my", label: "Malaysia", flag: "🇲🇾" },
  { value: "mx", label: "Mexico", flag: "🇲🇽" },
  { value: "ma", label: "Morocco", flag: "🇲🇦" },
  { value: "nl", label: "Netherlands", flag: "🇳🇱" },
  { value: "nz", label: "New Zealand", flag: "🇳🇿" },
  { value: "ng", label: "Nigeria", flag: "🇳🇬" },
  { value: "no", label: "Norway", flag: "🇳🇴" },
  { value: "pe", label: "Peru", flag: "🇵🇪" },
  { value: "ph", label: "Philippines", flag: "🇵🇭" },
  { value: "pl", label: "Poland", flag: "🇵🇱" },
  { value: "pt", label: "Portugal", flag: "🇵🇹" },
  { value: "qa", label: "Qatar", flag: "🇶🇦" },
  { value: "ro", label: "Romania", flag: "🇷🇴" },
  { value: "ru", label: "Russia", flag: "🇷🇺" },
  { value: "sa", label: "Saudi Arabia", flag: "🇸🇦" },
  { value: "sg", label: "Singapore", flag: "🇸🇬" },
  { value: "za", label: "South Africa", flag: "🇿🇦" },
  { value: "kr", label: "South Korea", flag: "🇰🇷" },
  { value: "es", label: "Spain", flag: "🇪🇸" },
  { value: "se", label: "Sweden", flag: "🇸🇪" },
  { value: "ch", label: "Switzerland", flag: "🇨🇭" },
  { value: "tw", label: "Taiwan", flag: "🇹🇼" },
  { value: "th", label: "Thailand", flag: "🇹🇭" },
  { value: "tr", label: "Turkey", flag: "🇹🇷" },
  { value: "gb", label: "United Kingdom", flag: "🇬🇧" },
  { value: "us", label: "United States", flag: "🇺🇸" },
  { value: "vn", label: "Vietnam", flag: "🇻🇳" },
].sort((a, b) => a.label.localeCompare(b.label));
